#!/bin/bash

uptown_set_path () {
   uptown_path="${uptown_path:-$PWD}"

   local -a new
   local -a longest

   IFS='/' read -r -a new <<< "$PWD"
   IFS='/' read -r -a longest <<< "$uptown_path"

   local new_len=${#new[@]}
   local longest_len=${#longest[@]}

   local match=-1
   while (( match+1 < new_len && match+1 < longest_len )); do
      [ "${longest[match+1]}" != "${new[match+1]}" ] && break
      (( match++ ))
   done

   if (( match < new_len-1 )); then
      uptown_path="$PWD"
      uptown_path_idx=$((new_len-1))
   else
      uptown_path_idx=$match
   fi
}

uptown_subpath_by_idx () {
   (( $# != 1 )) && return

   local -a path
   local idx
   local temp

   IFS='/' read -r -a path <<< "$uptown_path"

   if (( $1 < 0 || $1 >= ${#path[@]} )); then
      return 1
   elif (( $1 == 0 )); then
      echo -n "/"
   else
      idx=$(($1 + 1))
      temp=$(printf "/%s" "${path[@]:0:idx}")
      temp=${temp:1}
      echo -n "$temp"
   fi
}

cd_up () {
   builtin cd "$(uptown_subpath_by_idx $((uptown_path_idx-1)))"
}

cd_dn () {
   builtin cd "$(uptown_subpath_by_idx $((uptown_path_idx+1)))"
}
